# permissions for end users to edit lsfclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lsfcluster-editor-role
rules:
- apiGroups:
  - lsf.spectrumcomputing.ibm.com
  resources:
  - lsfclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lsf.spectrumcomputing.ibm.com
  resources:
  - lsfclusters/status
  verbs:
  - get
