#############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
#
---

# Make a LSF Cluster

# Create the Service Account
- include: lsf-sa-setup.yaml

# Create the network policy
- include: lsf-network.yaml

# Check the LSF PVC
- include: check-lsf-pvc.yaml

- include: service.yaml
  when: master.replicas != 0

- name: Generate the lsf-agent.yaml
  template:
    src: ../templates/lsf-agent.j2
    dest: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-agent.yaml"

- name: Generate the list of providers
  set_fact:
    allproviders: "{% set comp_resources = '' %}{% for comp in computes %}{% if comp.provider is defined and comp.provider is not none %}{{ comp.provider|join(' ') }} {% endif %}{% endfor %}"

- name: Generate the lsf-deployment.yaml
  template:
    src: ../templates/lsf-deployment.j2
    dest: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-deployment.yaml"

- name: Generate the lsf-gui.yaml
  template:
    src: ../templates/lsf-gui.j2
    dest: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-gui.yaml"

# Create the Pod Scheduler daemonsets
- include: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-agent.yaml"
  static: no

- include: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-deployment.yaml"
  static: no

- include: "{{ YAML_TEMP }}/{{ CNAME }}-lsf-gui.yaml"
  static: no

- include: lsf-gui-service.yaml
- include: lsf-gui-ingress.yaml
